gmap_web/urls.py
from django.urls import include, re_path

import gmap_web.views as views

urlpatterns = [
    re_path(r'^admin$', views.home, name='home'),
    re_path(r'^admin/reload/$', views.rld, name='rld'),
    re_path(r'^', include(('maps.urls', 'display_map'), namespace="display_map")),
    # re_path(r'^accounts/login/$', 'django.contrib.auth.views.login'),
]

maps/urls.py
from django.urls import path, re_path

from maps import views

app_name="maps"

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^description$', views.description, name='description'),
    re_path(r'^datasets$', views.datasets, name='datasets'),
    re_path(r'^about$', views.about, name='about'),
    re_path(r'^recent$', views.recent, name='recent'),
    path('map/<int:task_id>/', views.display_map, name='display_map'),
    re_path(r'^map/(\d*)/(\w*)$', views.display_map, name='display_map'),
    re_path(r'^get_map/(\d*)/$', views.get_map, name='get_map'),
    re_path(r'^get_map_zoomed/(\d*)$', views.get_map_zoomed, name='get_map_zoomed'),
    re_path(r'^get_task_metadata/(\d*)/$', views.get_task_metadata, name='get_task_metadata'),
    re_path(r'^get_json/(\d*)/$', views.get_json, name='get_json'),
    # re_path(r'^get_adjacency_matrix/(\d*)/$', views.get_adjacency_matrix, name='get_adjacency_matrix'),
    # re_path(r'^get_mds$', views.get_mds, name='get_mds'),
    re_path(r'^request_map/$', views.request_map, name='request_map')
    # re_path(r'^test$', views.test, name='test')
]

maps/models.py
from django.db import models
from json import dumps

class Task(models.Model):
    creation_date = models.CharField(null=True, max_length=64)
    creation_ip = models.CharField(null=True, max_length=64)

    input_dot = models.TextField()

    dot_rep = models.TextField()
    svg_rep = models.TextField()

    svg_rep0 = models.TextField(null=True)
    svg_rep1 = models.TextField(null=True)
    svg_rep2 = models.TextField(null=True)
    svg_rep3 = models.TextField(null=True)

    status = models.TextField()

    width = models.FloatField(null=True, blank=True)
    height = models.FloatField(null=True, blank=True)

    vis_type = models.CharField(max_length=64)
    layout_algorithm = models.CharField(max_length=64)
    cluster_algorithm = models.CharField(max_length=64)
    contiguous_algorithm = models.CharField(max_length=64)

    color_scheme  = models.CharField(max_length=64)
    semantic_zoom  = models.CharField(max_length=64)

    def metadata(self):
        return {
            'id': self.id,
            'status': self.status,
            'width': self.width,
            'height': self.height,
            'semantic_zoom': self.semantic_zoom,
        }

    def json_metadata(self):
        return dumps(self.metadata())

    def description(self):
        desc = ''
        desc += 'Visualization Type: ' + self.vis_type + '\n'
        desc += 'Layout Algorithm: ' + self.layout_algorithm + '\n'
        desc += 'Cluster Algorithm: ' + self.cluster_algorithm + '\n'
        desc += 'Color Scheme: ' + self.color_scheme + '\n'
        desc += 'Semantic Zoom: ' + self.semantic_zoom + '\n'
        return desc

maps/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from lib.web_interface import create_task, create_map, get_formatted_map
from lib.interface import CallExternalException
from maps.models import Task
#import thread
import time
import json
import pygraphviz
from time import strftime
import networkx as nx
from networkx.readwrite import json_graph
from networkx.drawing import nx_agraph

def index(request):
	return render(request, 'maps/index.html')

def test(request):
	return render(request, 'maps/sphericalTest.html')

def description(request):
	return render(request, 'description.html')

def datasets(request):
	return render(request, 'datasets.html')

def about(request):
	return render(request, 'about.html')

def recent(request):
	map_list = []

	debug = request.GET.get('debug', 'false')
	page = int(request.GET.get('page', '0'))
	items_per_page = 30
	start = items_per_page*page
	end = start + items_per_page

	for task in Task.objects.order_by('-id')[start:end]:
		obj = {}
		obj['id'] = task.id
		obj['link'] = '/map/' + str(task.id)
		if len(task.input_dot) < 75:
			obj['dot'] = task.input_dot
		else:
			obj['dot'] = task.input_dot[:75] + '...'
		obj['dot_link'] = '/map/' + str(task.id) + '/input_dot'
		obj['date'] = task.creation_date
		obj['ip'] = task.creation_ip
		obj['status'] = task.status
		obj['status_link'] = '/map/' + str(task.id) + '/input_desc'
		obj['delete_link'] = '/delete_map/' + str(task.id)
		map_list.append(obj)
	return render(request, 'maps/recent.html', {'map_list': map_list, 'debug': debug})


def request_map(request):
	log.debug(f"request_map called with method: {request.method}")
	if request.method == 'POST':
		try:
			#log.debug(f"POST data: {dict(request.POST.items())}")
			task = create_task(dict(request.POST.items()), request.META.get('REMOTE_ADDR', ''))
			log.debug(f"Task created with ID: {task.id if hasattr(task, 'id') else 'unknown'}")
			try:
				import threading
				log.debug(f"Starting create_map thread for task ID: {task.id if hasattr(task, 'id') else 'unknown'}")
				threading.Thread(target=create_map,
				    args=(task,1),
				).start()
			except Exception as e:
				log.error(f"Thread start error: {str(e)}")
				print ('thread-error: ' + str(e))
			return redirect('/map/' + str(task.id) + '/')
		except CallExternalException as e:
			log.error(f"CallExternalException: {str(e)}")
			return render(request, 'maps/error.html', {'msg': str("<br />".join(str(e).split("\n")))})
		log.debug(f"Task creation and threading completed for task ID: {task.id if hasattr(task, 'id') else 'unknown'}")
		return redirect('/map/' + str(task.id) + '/')
	log.debug("request_map did not process POST request")
	return render(request, 'maps/error.html', {'msg': 'Invalid request method.'})

MIME_TYPES = {
    'pdf': 'application/pdf',
    'ps':  'application/postscript',
    'eps': 'application/postscript',
    'png': 'image/png',
    'gif': 'image/gif',
    'jpg': 'image/jpeg',
    'svg': 'image/svg+xml',
    'dot': 'text/plain',
    'gv':  'text/plain',
}

def display_map(request, task_id, format = ''):
	if request.method == 'GET':
		task = get_object_safe(task_id, 10)
		print("I am trying to display map")

		if format == '':
			# if task.layout_algorithm == 'SGD':
			# 	return render(request,'maps/SGD_display.html',{'task':task})
			# elif task.layout_algorithm == 'neato':
			# 	return render(request,'maps/hyperbolic.html',{'task':task})
			# return render(request, 'maps/hyperbolic.html',{'task': task});
			# if task.contiguous_algorithm == 'true':
			# 	return render(request, 'maps/spherical.html', {'task': task})
			# elif task.hyperbolic_projection == 'true':
			# 	return render(request, 'maps/hyperbolic.html',{'task': task})
			print("task is printed")
			print(task.json_metadata())
			return render(request, 'maps/map.html', {'task': task})
		else:
			if format in MIME_TYPES:
				content = get_formatted_map(task, format)
				return HttpResponse(content, content_type = MIME_TYPES[format])
			elif format == 'input_dot':
				return HttpResponse(task.input_dot, 'text/plain')
			elif format == 'input_desc':
				return HttpResponse(task.description(), 'text/plain')

def get_json(request, task_id):
	if request.method == 'GET':
		task = Task.objects.get(id = task_id)
		#print(task.description())
		dot_graph = nx_agraph.from_agraph(pygraphviz.AGraph(task.dot_rep))
		print(task.dot_rep)
		graph_json = json.dumps(json_graph.node_link_data(dot_graph))
		# graph_json = json.dumps(task.dot_rep)

		return HttpResponse(graph_json, content_type='application/json')

#def get_adjacency_matrix(request, task_id):
#	if request.method == 'POST':
#		task = Task.objects.get(id = task_id)
#		print dot_to_adjacency_matrix(pygraphviz.AGraph(task.dot_rep))

#def get_mds(request):
#	return HttpResponse(json.dumps(testMDS()), content_type='application/json')

def get_task_metadata(request, task_id):
	if request.method == "GET":
		task = Task.objects.get(id=task_id)
		print(task.json_metadata())
		return HttpResponse(task.json_metadata(), content_type='application/json')

def get_map(request, task_id):
	if request.method == 'GET':
		print(task_id)
		task = Task.objects.get(id = task_id)
		return HttpResponse(u'%s' % task.svg_rep, content_type="image/svg+xml")

import logging
log = logging.getLogger('gmap_web')

def get_map_zoomed(request, task_id):
    if request.method == 'GET':
        log.debug(f"get_map_zoomed called for task_id={task_id}")
        zoom = request.GET.get('zoom', '3')
        log.debug(f"Requested zoom level: {zoom}")
        task = get_object_safe(task_id, 10)
        svg = None
        if zoom == '0':
            svg = getattr(task, 'svg_rep0', None)
        elif zoom == '1':
            svg = getattr(task, 'svg_rep1', None)
        elif zoom == '2':
            svg = getattr(task, 'svg_rep2', None)
        elif zoom == '3':
            svg = getattr(task, 'svg_rep3', None)
        log.debug(f"SVG for zoom {zoom}: {'set' if svg else 'not set'}; length: {len(svg) if svg else 0}")
        if not svg:
            log.warning(f"No SVG found for zoom {zoom}, returning empty SVG.")
            # Return a minimal valid SVG if missing, to avoid XML parsing errors
            return HttpResponse('<svg xmlns="http://www.w3.org/2000/svg"></svg>', content_type="image/svg+xml")
        return HttpResponse(svg, content_type="image/svg+xml")

def get_object_safe(task_id, attempt):
	if attempt <= 0:
		return get_object_or_404(Task, id = task_id)

	try:
		task = get_object_or_404(Task, id = task_id)
		return task
	except Exception as e:
		if type(e).__name__ != 'OperationalError':
			raise e
		print (type(e).__name__ + ': ' + str(e))
		time.sleep(0.1)
		return get_object_safe(task_id, attempt - 1)

def delete_map(request, task_id):
	if request.method == 'GET':
		task = Task.objects.get(id = task_id)
		task.delete();
		return recent(request)

maps/templates/maps/SGD_display.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block title %}{{ block.super }} :: map{% endblock %}

{% block js %}
{{ block.super }}
{% load static %}
<html>
  <head>
    <title>Hyperbolic Canvas Example</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="{% get_static_prefix %}css/hyperbolic/example.css">
  </head>
  <body>

    <div id="hyperbolic-canvas"></div>

    <script src="{% get_static_prefix %}js/d3.min.js"></script>

    <script type="text/javascript" src="{% get_static_prefix %}js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="{% get_static_prefix %}js/jquery-ui-1.10.3.custom.min.js"></script>

    <script src="{% get_static_prefix %}openlayers/OpenLayers-min.js"></script>
    <script src="{% get_static_prefix %}openlayers/InlineXhtml/lib/OpenLayers/Tile/InlineXhtml.js"></script>
    <script src="{% get_static_prefix %}openlayers/InlineXhtml/lib/OpenLayers/Layer/ScalableInlineXhtml.js"></script>

    <script type="application/javascript" src="{% get_static_prefix %}js/hyperbolic_canvas.js"></script>

    <script src="{% get_static_prefix %}js/math.js"></script>

    <script src="{% get_static_prefix %}js/graphlib-dot.js"></script>

    <script src="{% get_static_prefix %}js/dotparser.min.js"></script>

    <script type="text/javascript">

    var parsed = true, opacity = 100, graticule, width, height, node, link, borders, fills, projection, inverseProjection, path, svgGraticule, svg, jsongraph, chunk, MINWIDTH = 0, MAXWIDTH = 16, MINFONT = 10, MAXFONT = 16, fontsize;
    var polygons = [[]];
    var colors = [];
    var lines = [[]];

    function get_map(delay) {
        $.ajax({
            dataType: "json",
            type: "GET",
            url: "{% url 'maps:get_task_metadata' task.id %}",
            async: true,
            cache: false,
            timeout: 300000,
            success: function (task) {
              if (task.status == 'completed') {
                    $('#status_indicator').hide();
                    return(display_map("{% url 'maps:get_json' task.id %}", task.width, task.height))
                }
                else {
                    $('#status_text').html('Status: ' + task.status);
                    console.log(task)
                    if (task.status.indexOf("error") != 0)
                        setTimeout(get_map, delay, Math.min(delay * 2, 5000));
                    else
                        $('#status_indicator').hide();
                }
            },
            // handle error
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                //alert(textStatus + " " + errorThrown);
                // try again in 10 seconds if there was a request error
                setTimeout(get_map, delay, Math.min(delay * 2, 5000));
            },
        });
    }

    function display_map(map_url, width, height) {
        $.ajax({
            dataType: "json",
            type: "GET",
            url: map_url,
            async: true,
            cache: false,
            timeout: 300000,
            success: function (task) {



                jsongraph = task;
                //drawGraph(jsongraph);
                $('#status').hide();
                loadScript(jsongraph);
                return(jsongraph)
            },
            // handle error
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                //alert(textStatus + " " + errorThrown);
                // try again in 10 seconds if there was a request error
                setTimeout(display_map, map_url, width, height, 100, Math.min(100 * 2, 5000));
            },
        });
    }

    var loadScript = function(graph){
      var scriptName = 'SGD_inter';
      var script = document.createElement('script');
      script.onload = function () {
        var canvas = HyperbolicCanvas.create('#hyperbolic-canvas', scriptName);
        graph = graph.replaceAll("'",'"')
        HyperbolicCanvas.scripts[scriptName](canvas,graph);
      };
      script.onerror = function () {
        var canvas = HyperbolicCanvas.create('#hyperbolic-canvas', scriptName);
        alert('No script found with the name "' + scriptName + '".');
      };

      script.src = "../../static/scripts/" + scriptName + '.js';
      document.body.appendChild(script);
    }

      var getQueryVariable = function (variable) {
        // https://css-tricks.com/snippets/javascript/get-url-variables/
        var query = window.location.search.substring(1);
        var vars = query.split("&");
        for (var i=0;i<vars.length;i++) {
          var pair = vars[i].split("=");
          if(pair[0] == variable){return pair[1];}
        }
        return('poincare_disk');
      };

      var ready = function (fn) {
        if (document.readyState != 'loading'){
          fn();
        } else {
          document.addEventListener('DOMContentLoaded', fn);
        }
      };

      ready(function () {

        width = window.innerWidth;
        height = window.innerHeight;



        graph = get_map(100);
        console.log(graph)
      });

      var clickResetButton = function(){
        if (document.getElementById("resetMap").value === "Reset"){
          document.getElementById("resetMap").value = "NeedsReset"
        }
      }

      var clickSaveButton = function(){
        var canvas1 = document.getElementById('hyperbolic-canvas');
        var dataURL = canvas1.toDataURL();
      }
    </script>

  </body>
</html>
{% endblock %}
{% block content %}
<div id="status" class="status">
    <img id="status_indicator" src="{% get_static_prefix %}img/load_indicator.gif" width="16px" height="16px">
    <span id="status_text">Status: loading</span>
</div>
<div id="content">
<label for="transparency" id="transparencyLabel">Edge transparency</label>
<input type="range" min="0" max="100" value="100" class="slider" id="transparency"/>

<label for="nodesVisible" id="nodesVisibleLabel">Label size</label>
<input type="range" min="0" max="40" value="15" class="slider" id="nodesVisible"/>

</div>

{% endblock %}

maps/templates/maps/error.html
{% extends "base.html" %}
{% block content %}
<div style="margin: 20px">
 <h3>An error has occured. Please contact *@email.arizona.edu if this was unexpected.</h3>
 <br>
 Stack trace:
 <p>
 	{{msg|safe}}
 </p>
</div>
{% endblock %}

maps/templates/maps/map.html
{% extends "base.html" %}
{% block title %}{{ block.super }} :: map{% endblock %}

{% block js %}
    {{ block.super }}
    {% load static %}
    <link href="{% get_static_prefix%}css/ui-lightness/jquery-ui-1.10.3.custom.min.css" rel="stylesheet">
	<script type="text/javascript" src="{% get_static_prefix %}js/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="{% get_static_prefix %}js/jquery-ui-1.10.3.custom.min.js"></script>

    <script src="{% get_static_prefix %}openlayers/OpenLayers-min.js"></script>
    <script src="{% get_static_prefix %}openlayers/InlineXhtml/lib/OpenLayers/Tile/InlineXhtml.js"></script>
    <script src="{% get_static_prefix %}openlayers/InlineXhtml/lib/OpenLayers/Layer/ScalableInlineXhtml.js"></script>

<script type="text/javascript">
$(document).ready(function() {
    console.log('Document ready');
	get_map(100);
    $('#opacity-slider').slider({ 
         max:100,
         min:0,
         value:100,
         animate: true,
         change: opacity_slider_change,
    });
});

function opacity_slider_change(event, ui) {
    var opacity =  ui.value / 100.0;
    $('.edge').children('path').attr('opacity', opacity);
}

var SVG_ZOOM_LEVELS = 4;
var VIEW_ZOOM_LEVELS = 5;

function get_map(delay) {
    console.log('Calling get_map with delay', delay);
    $.ajax({
        dataType: "json",
        type: "GET",
        url: "{% url 'maps:get_task_metadata' task.id %}",
        async: true,
        cache: false,
        timeout: 300000,
        success: function(task) {
            console.log('AJAX success, task:', task);
        	if (task.status == 'completed') {
                console.log("task completed")
                if (task.semantic_zoom === 'false' ) // || task.semantic_zoom === ""
                {
                    console.log('Calling display_map with', "{% url 'maps:get_map' task.id %}", task.width, task.height);
                    display_map("{% url 'maps:get_map' task.id %}", task.width, task.height);
                }
                else
                {
                    var urls = [];
                    for (var i = 0; i < SVG_ZOOM_LEVELS; i++) {
                        var url = "{% url 'maps:get_map_zoomed' task.id %}?zoom=" + i;
                        console.log('Adding zoomed url:', url);
                        urls.push(url);
                    }
                    console.log('Calling display_map_with_zoom with', urls, task.width, task.height);
                    display_map_with_zoom(urls, task.width, task.height);
                }
                $('#status').hide();
            }
            else {
                console.log('Task not completed:', task)
                $('#status_text').html('Status: ' + task.status);
                if (task.status.indexOf("error") != 0)
                    setTimeout(get_map, delay, Math.min(delay*2, 5000));
                else
                    $('#status_indicator').hide();
            }
        },
        // handle error
        error: function(XMLHttpRequest, textStatus, errorThrown) {
            console.log('AJAX error', textStatus, errorThrown);
            // try again in 10 seconds if there was a request error
            setTimeout(get_map, delay, Math.min(delay*2, 5000));
        },
    });
}

function display_map(url, width, height) {
    console.log('display_map called with url:', url, 'width:', width, 'height:', height);
    // Remove any previous SVG
    $('#svg_map').remove();
    // Fetch the SVG and insert it into the DOM
    $.ajax({
        url: url,
        type: 'GET',
        dataType: 'text',
        success: function(svg) {
            console.log('SVG fetched:', svg.substring(0, 200)); // Log first 200 chars
            var container = document.getElementById('map_container');
            if (!container) {
                console.log('No #map_container found, creating one.');
                container = document.createElement('div');
                container.id = 'map_container';
                document.body.appendChild(container);
            }
            container.innerHTML = svg;
            // Optionally set width/height if needed
            if (width && height) {
                var svgElem = container.querySelector('svg');
                if (svgElem) {
                    svgElem.setAttribute('width', width);
                    svgElem.setAttribute('height', height);
                }
            }
        },
        error: function(xhr, status, error) {
            console.log('Error fetching SVG:', status, error);
        }
    });
}

function display_map_with_zoom(map_urls, width, height) {
    console.log('display_map_with_zoom called with', map_urls, width, height);
	var scale0 = Math.max(height/(window.innerHeight - 80), width/(window.innerWidth));
	var S = 0.7;
	var res = [scale0];
	for (var i = 1; i < VIEW_ZOOM_LEVELS; i++)
		res.push(res[i-1] * S);

    var bounds = new OpenLayers.Bounds(0, -1 * height, width, 0);
    map_options = {
        controls:[
            new OpenLayers.Control.Navigation(),
            new OpenLayers.Control.PanZoomBar(),
                ],
        //maxExtent: bounds,
        //numZoomLevels: 5,
        fractionalZoom: true,
        resolutions: res,
    }
    console.log('Creating OpenLayers.Map with options', map_options);
    map = new OpenLayers.Map ("map", map_options);

    var gmaps = new Array();
    for (var i = 0; i < SVG_ZOOM_LEVELS; i++)
    {
        console.log('Adding ScalableInlineXhtml layer', map_urls[i]);
	    var gmap = new OpenLayers.Layer.ScalableInlineXhtml(
	        "GMap",
	    	map_urls[i],
	    	bounds,
	        null,
	    	{isBaseLayer: true, opacity: '1.0'});
	    gmap.adjustBounds(bounds);

	    gmaps.push(gmap);
    }

    var svg = $('svg');
    map.addLayers(gmaps);
	for (var i = 0; i < gmaps.length; i++)
		gmaps[i].setVisibility(false);
    map.zoomToExtent(bounds);

    var curZoom = getZoomSafe(0, gmaps.length - 1, map.getZoom());
    gmaps[curZoom].setVisibility(true);

	map.events.register("zoomend", map, function() {
		zoom = map.getZoom();
	    for (var i = 0; i < gmaps.length; i++)
	    	gmaps[i].setVisibility(false);

	    zoom = getZoomSafe(0, gmaps.length - 1, map.getZoom());
		gmaps[zoom].setVisibility(true);
	});
    console.log('display_map_with_zoom finished');
}

function getZoomSafe(lower, upper, value)
{
    var zoom = value.toFixed();
    zoom = Math.max(lower, zoom);
    zoom = Math.min(upper, zoom);
    return zoom;
}

</script>
{% endblock %}

{% block content %}
    <div id= 'opacity' style="margin-left: 10px; margin-top: 5px; margin-bottom: 5px">
        <h4 style="margin: 0px">Edge Opacity:</h4> <div id='opacity-slider' class='small_slider'></div>
    </div>

    <div id="status" class="status" >
		<img id="status_indicator" src="{% get_static_prefix %}img/load_indicator.gif" width="16px" height="16px">
    	<span id="status_text">Status: loading</span>
    </div>
    <div id='map' >
		<script>
			var el = document.getElementById('map');
			el.style.height = (window.innerHeight - 80) + "px";
		</script>
    </div>

<h4 style="position: absolute; top: 20px; right: 10px;">
Save as <a href="./dot" download="map.dot">dot</a> 
		<a href="./svg" download="map.svg">svg</a> 
		<a href="./png" download="map.png">png</a> 
		<a href="./pdf" download="map.pdf">pdf</a>
</h4>
{% endblock %}

maps/templates/maps/recent.html
{% extends "base.html" %}
{% block title %}{{ block.super }} :: Recent maps{% endblock %}

{% block js %}
{% load static %}
{% endblock %}

{% block content %}
	<div class="description">
		<h2 style="text-align:center">Recently Created Maps</h2>

		<table class="latest">
			<tbody>
				<tr>
					<td width="8%" align="center"><b>id</b></td>
					<td width="{% if debug = 'true' %}19%{% else %}30%{% endif %}" align="center"><b>creation date</b></td>
					<td width="{% if debug = 'true' %}49%{% else %}60%{% endif %}" align="center"><b>source</b></td>
					{% if debug = 'true' %}<td width="8%" align="center"><b>ip</b></td>{% endif %}
					{% if debug = 'true' %}<td width="8%" align="center"><b>status</b></td>{% endif %}
					{% if debug = 'true' %}<td width="8%" align="center"><b>delete</b></td>{% endif %}
				</tr>

				{% for obj in map_list %}
			    <tr>
			    	<td><a href="{{obj.link}}">{{ obj.id }}</a></td>
					<td>{{ obj.date }}</td>
					<td align="left"><a href="{{obj.dot_link}}">{{ obj.dot }}</a></td>
					{% if debug = 'true' %}<td align="center">{{ obj.ip }}{% endif %}
					{% if debug = 'true' %}<td align="center"><a href="{{obj.status_link}}">{{ obj.status }}</a>{% endif %}
					{% if debug = 'true' %}<td align="center"><a href="{{obj.delete_link}}">del {{ obj.id }}</a>{% endif %}
			    </tr>
				{% endfor %}

			</tbody>
		</table>

	</div>
{% endblock %}