gmap_web/urls.py
from django.urls import include, re_path

import gmap_web.views as views

urlpatterns = [
    re_path(r'^admin$', views.home, name='home'),
    re_path(r'^admin/reload/$', views.rld, name='rld'),
    re_path(r'^', include(('maps.urls', 'display_map'), namespace="display_map")),
    # re_path(r'^accounts/login/$', 'django.contrib.auth.views.login'),
]

maps/urls.py
from django.urls import path, re_path

from maps import views

app_name="maps"

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^description$', views.description, name='description'),
    re_path(r'^datasets$', views.datasets, name='datasets'),
    re_path(r'^about$', views.about, name='about'),
    re_path(r'^recent$', views.recent, name='recent'),
    path('map/<int:task_id>/', views.display_map, name='display_map'),
    re_path(r'^map/(\d*)/(\w*)$', views.display_map, name='display_map'),
    re_path(r'^get_map/(\d*)/$', views.get_map, name='get_map'),
    re_path(r'^get_map_zoomed/(\d*)$', views.get_map_zoomed, name='get_map_zoomed'),
    re_path(r'^get_task_metadata/(\d*)/$', views.get_task_metadata, name='get_task_metadata'),
    re_path(r'^get_json/(\d*)/$', views.get_json, name='get_json'),
    # re_path(r'^get_adjacency_matrix/(\d*)/$', views.get_adjacency_matrix, name='get_adjacency_matrix'),
    # re_path(r'^get_mds$', views.get_mds, name='get_mds'),
    re_path(r'^request_map/$', views.request_map, name='request_map')
    # re_path(r'^test$', views.test, name='test')
]

maps/models.py
from django.db import models
from json import dumps

class Task(models.Model):
    creation_date = models.CharField(null=True, max_length=64)
    creation_ip = models.CharField(null=True, max_length=64)

    input_dot = models.TextField()

    dot_rep = models.TextField()
    svg_rep = models.TextField()

    svg_rep0 = models.TextField(null=True)
    svg_rep1 = models.TextField(null=True)
    svg_rep2 = models.TextField(null=True)
    svg_rep3 = models.TextField(null=True)

    status = models.TextField()

    width = models.FloatField(null=True, blank=True)
    height = models.FloatField(null=True, blank=True)

    vis_type = models.CharField(max_length=64)
    layout_algorithm = models.CharField(max_length=64)
    cluster_algorithm = models.CharField(max_length=64)
    contiguous_algorithm = models.CharField(max_length=64)

    color_scheme  = models.CharField(max_length=64)
    semantic_zoom  = models.CharField(max_length=64)

    def metadata(self):
        return {
            'id': self.id,
            'status': self.status,
            'width': self.width,
            'height': self.height,
            'semantic_zoom': self.semantic_zoom,
        }

    def json_metadata(self):
        return dumps(self.metadata())

    def description(self):
        desc = ''
        desc += 'Visualization Type: ' + self.vis_type + '\n'
        desc += 'Layout Algorithm: ' + self.layout_algorithm + '\n'
        desc += 'Cluster Algorithm: ' + self.cluster_algorithm + '\n'
        desc += 'Color Scheme: ' + self.color_scheme + '\n'
        desc += 'Semantic Zoom: ' + self.semantic_zoom + '\n'
        return desc

maps/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from lib.web_interface import create_task, create_map, get_formatted_map
from lib.interface import CallExternalException
from maps.models import Task
#import thread
import time
import json
import pygraphviz
from time import strftime
import networkx as nx
from networkx.readwrite import json_graph
from networkx.drawing import nx_agraph

def index(request):
	return render(request, 'maps/index.html')

def test(request):
	return render(request, 'maps/sphericalTest.html')

def description(request):
	return render(request, 'description.html')

def datasets(request):
	return render(request, 'datasets.html')

def about(request):
	return render(request, 'about.html')

def recent(request):
	map_list = []

	debug = request.GET.get('debug', 'false')
	page = int(request.GET.get('page', '0'))
	items_per_page = 30
	start = items_per_page*page
	end = start + items_per_page

	for task in Task.objects.order_by('-id')[start:end]:
		obj = {}
		obj['id'] = task.id
		obj['link'] = '/map/' + str(task.id)
		if len(task.input_dot) < 75:
			obj['dot'] = task.input_dot
		else:
			obj['dot'] = task.input_dot[:75] + '...'
		obj['dot_link'] = '/map/' + str(task.id) + '/input_dot'
		obj['date'] = task.creation_date
		obj['ip'] = task.creation_ip
		obj['status'] = task.status
		obj['status_link'] = '/map/' + str(task.id) + '/input_desc'
		obj['delete_link'] = '/delete_map/' + str(task.id)
		map_list.append(obj)
	return render(request, 'maps/recent.html', {'map_list': map_list, 'debug': debug})


def request_map(request):
	log.debug(f"request_map called with method: {request.method}")
	if request.method == 'POST':
		try:
			#log.debug(f"POST data: {dict(request.POST.items())}")
			task = create_task(dict(request.POST.items()), request.META.get('REMOTE_ADDR', ''))
			log.debug(f"Task created with ID: {task.id if hasattr(task, 'id') else 'unknown'}")
			try:
				import threading
				log.debug(f"Starting create_map thread for task ID: {task.id if hasattr(task, 'id') else 'unknown'}")
				threading.Thread(target=create_map,
				    args=(task,1),
				).start()
			except Exception as e:
				log.error(f"Thread start error: {str(e)}")
				print ('thread-error: ' + str(e))
			return redirect('/map/' + str(task.id) + '/')
		except CallExternalException as e:
			log.error(f"CallExternalException: {str(e)}")
			return render(request, 'maps/error.html', {'msg': str("<br />".join(str(e).split("\n")))})
		log.debug(f"Task creation and threading completed for task ID: {task.id if hasattr(task, 'id') else 'unknown'}")
		return redirect('/map/' + str(task.id) + '/')
	log.debug("request_map did not process POST request")
	return render(request, 'maps/error.html', {'msg': 'Invalid request method.'})

MIME_TYPES = {
    'pdf': 'application/pdf',
    'ps':  'application/postscript',
    'eps': 'application/postscript',
    'png': 'image/png',
    'gif': 'image/gif',
    'jpg': 'image/jpeg',
    'svg': 'image/svg+xml',
    'dot': 'text/plain',
    'gv':  'text/plain',
}

def display_map(request, task_id, format = ''):
	if request.method == 'GET':
		task = get_object_safe(task_id, 10)
		print("I am trying to display map")

		if format == '':
			# if task.layout_algorithm == 'SGD':
			# 	return render(request,'maps/SGD_display.html',{'task':task})
			# elif task.layout_algorithm == 'neato':
			# 	return render(request,'maps/hyperbolic.html',{'task':task})
			# return render(request, 'maps/hyperbolic.html',{'task': task});
			# if task.contiguous_algorithm == 'true':
			# 	return render(request, 'maps/spherical.html', {'task': task})
			# elif task.hyperbolic_projection == 'true':
			# 	return render(request, 'maps/hyperbolic.html',{'task': task})
			print("task is printed")
			print(task.json_metadata())
			return render(request, 'maps/map.html', {'task': task})
		else:
			if format in MIME_TYPES:
				content = get_formatted_map(task, format)
				return HttpResponse(content, content_type = MIME_TYPES[format])
			elif format == 'input_dot':
				return HttpResponse(task.input_dot, 'text/plain')
			elif format == 'input_desc':
				return HttpResponse(task.description(), 'text/plain')

def get_json(request, task_id):
	if request.method == 'GET':
		task = Task.objects.get(id = task_id)
		#print(task.description())
		dot_graph = nx_agraph.from_agraph(pygraphviz.AGraph(task.dot_rep))
		print(task.dot_rep)
		graph_json = json.dumps(json_graph.node_link_data(dot_graph))
		# graph_json = json.dumps(task.dot_rep)

		return HttpResponse(graph_json, content_type='application/json')

#def get_adjacency_matrix(request, task_id):
#	if request.method == 'POST':
#		task = Task.objects.get(id = task_id)
#		print dot_to_adjacency_matrix(pygraphviz.AGraph(task.dot_rep))

#def get_mds(request):
#	return HttpResponse(json.dumps(testMDS()), content_type='application/json')

def get_task_metadata(request, task_id):
	if request.method == "GET":
		task = Task.objects.get(id=task_id)
		print(task.json_metadata())
		return HttpResponse(task.json_metadata(), content_type='application/json')

def get_map(request, task_id):
	if request.method == 'GET':
		print(task_id)
		task = Task.objects.get(id = task_id)
		return HttpResponse(u'%s' % task.svg_rep, content_type="image/svg+xml")

import logging
log = logging.getLogger('gmap_web')

def get_map_zoomed(request, task_id):
    if request.method == 'GET':
        log.debug(f"get_map_zoomed called for task_id={task_id}")
        zoom = request.GET.get('zoom', '3')
        log.debug(f"Requested zoom level: {zoom}")
        task = get_object_safe(task_id, 10)
        svg = None
        if zoom == '0':
            svg = getattr(task, 'svg_rep0', None)
        elif zoom == '1':
            svg = getattr(task, 'svg_rep1', None)
        elif zoom == '2':
            svg = getattr(task, 'svg_rep2', None)
        elif zoom == '3':
            svg = getattr(task, 'svg_rep3', None)
        log.debug(f"SVG for zoom {zoom}: {'set' if svg else 'not set'}; length: {len(svg) if svg else 0}")
        if not svg:
            log.warning(f"No SVG found for zoom {zoom}, returning empty SVG.")
            # Return a minimal valid SVG if missing, to avoid XML parsing errors
            return HttpResponse('<svg xmlns="http://www.w3.org/2000/svg"></svg>', content_type="image/svg+xml")
        return HttpResponse(svg, content_type="image/svg+xml")

def get_object_safe(task_id, attempt):
	if attempt <= 0:
		return get_object_or_404(Task, id = task_id)

	try:
		task = get_object_or_404(Task, id = task_id)
		return task
	except Exception as e:
		if type(e).__name__ != 'OperationalError':
			raise e
		print (type(e).__name__ + ': ' + str(e))
		time.sleep(0.1)
		return get_object_safe(task_id, attempt - 1)

def delete_map(request, task_id):
	if request.method == 'GET':
		task = Task.objects.get(id = task_id)
		task.delete();
		return recent(request)

maps/templates/about.html
{% extends "base.html" %}
{% block title %}{{ block.super }} :: About{% endblock %}

{% block js %}
{% load static %}
{% endblock %}

{% block content %}
	<div class="description" style="text-align:center;">
		<h2 style="text-align:center">People behind the system</h2>
		<div class='row'>
			<div class='photo'>
				<a href="http://www.cs.arizona.edu/~kobourov/">
				<img src="{% get_static_prefix %}photos/stephen.jpg" class="img-about" /></a><br>
				Stephen Kobourov
			</div>
			<div class='about-info'>
			Stephen Kobourov is a Professor of Computer Science at the University of Arizona. 
			He works on graph drawing and information visualization, geometric algorithms and data
			 structures, human computer interaction, and pervasive computing.</div>
		</div>

		<!--div class='row'>
			<div class='photo'>
				<a href="http://www.cs.arizona.edu/~jfowler">
					<img src="{% get_static_prefix %}photos/joe.jpg" class="img-about" /></a><br>
				Joe Fowler
			</div>

			<div class='about-info'>Joe is a post-doc at the University of Arizona. His main research interests include graph drawing and 
			visualization, computational geometry, sensor networks, and graph-based algorithms.</div>
		</div-->

		<div class='row'>
			<div class='photo'>
				<a href="http://www.cs.arizona.edu/~spupyrev/">
					<img src="{% get_static_prefix %}photos/sergey.jpg" class="img-about" /></a><br>
				Sergey Pupyrev
			</div>

			<div class='about-info'>Sergey Pupyrev is a post-doc at the University of Arizona.
			 He works on graph drawing and graph algorithms.</div>
		</div>

		<div class='row'>
			<div class='photo'>
				<a href="http://www.cs.arizona.edu/~paolosimonetto">
					<img src="{% get_static_prefix %}photos/paolo.jpg" class="img-about" /></a><br>
				Paolo Simonetto
			</div>

			<div class='about-info'>Paolo Simonetto is a post-doc at the University of Arizona.
			His current research interests are graph drawing and the generation of maps and diagrams.
			</div>
		</div>
	</div>
{% endblock %}

maps/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta name="title" content="Web-GMap">
		<meta name="keywords" content="network, network visualization, graph drawing, graph visualization, map, gmap, generator, graphviz, online">
		<meta name="description" content="GMap is an algorithm that turns underlying graph structural information, clustering, and neighborhoods into geographic maps, which are intuitive to most people">

        <title>{% block title %}Web-GMap{% endblock %}</title>

		<link type="image/ico" rel="shortcut icon" href="{% get_static_prefix%}/img/favicon.ico" />
        <link href="{% get_static_prefix%}css/bootstrap.css" rel="stylesheet">

		<script type="text/javascript" src="{% get_static_prefix %}js/ga.js"></script>

        {% block js %}
        {% endblock %}
    </head>

    <body>
		<div id="header" class="navbar navbar-static-top" style="visibility:hidden">
			<div class="navbar-inner">
				<ul class="nav">
					<li><a href="{% url 'maps:index' %}">Home</a></li>
					<li><a href="{% url 'maps:description' %}">Description</a></li>
					<li><a href="{% url 'maps:datasets' %}">Datasets</a></li>
					<li><a href="{% url 'maps:about' %}">About Us</a></li>
				</ul>
			</div>
		</div>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

    <div id="content">{% block content %}{% endblock %}</div>
</body>
</html>

maps/templates/description.html
{% extends "base.html" %}
{% block title %}{{ block.super }} :: Description{% endblock %}

{% block js %}
{% load static %}
{% endblock %}

{% block content %}
	<div class="description">
		<h2 style="text-align:center">What is GMap?</h2>
		<p style="text-align:justify">GMap is an algorithm for visualizing graphs as maps. Information visualization can be invaluable in making sense out of 
		large data sets. However, traditional graph visualization methods often fail to capture the underlying structural information, 
		clustering, and neighborhoods. GMap, provides a way to overcome some of the shortcomings with the help of the geographic map 
		metaphor. While graphs, charts, and tables often require considerable effort to comprehend, a map representation is more 
		intuitive, as most people are very familiar with maps and even enjoy carefully examining maps. The effectiveness of GMap is 
		illustrated with examples from several domains, namely TV shows, Amazon books, and last.fm music.
		</p>

		<h4>Examples</h2>
		<div style="text-align:center">
			<a href="{% get_static_prefix %}img/MusicLand.png"><img src="{% get_static_prefix %}img/MusicLand_small.png"  style="max-height: 250px"/></a>
			&nbsp;&nbsp;&nbsp;
			<a href="{% get_static_prefix %}img/MusicLand.png"><img src="{% get_static_prefix %}img/MusicLand_small2.png"  style="max-height: 250px"/></a>
			<p>	This map of music shows relations between musicians/groups. Related musicians are closeby and in the same country.</p>
		</div>

		See also the list of <a href="{% url 'maps:recent' %}">recently created</a> maps.

		<h4>Algorithms and Implementation</h2>
		<p style="text-align:justify">The system relies on a model behind drawing clustered graphs. The GMap framework combines graph layout and graph clustering, together
		with appropriate coloring of the clusters and creating boundaries based on clusters and connectivity in the
		original graph. The approach can be generalized to any relational data set. In GMap the visualization is based on a modified Voronoi diagram of the 
		nodes, which in turn is determined by the embedding and clustering. The algorithms are described in a series of research papers:
			<ul>
				<li>
					<a href="http://www.cs.arizona.edu/~kobourov/recsys09.pdf">Putting Recommendations on the Map - Visualizing Clusters and Relations</a>
				</li>

				<li>
					<a href="http://www.cs.arizona.edu/~kobourov/pacvis10.pdf">GMap: Visualizing Graphs and Clusters as Maps</a>
				</li>

				<li>
					<a href="http://www.cs.arizona.edu/~kobourov/pacvis11.pdf">Visualizing Dynamic Data with Maps</a>
				</li>

				<li>
					<a href="ftp://ftp.cs.arizona.edu/reports/2014/TR14-02.pdf">Visualizing Graphs as Maps with Contiguous Regions</a>,
					a <a href="{% get_static_prefix %}media/cont-maps-video.mp4">video</a> accompanying the paper with more details
					
				</li>

			</ul>

			<br>
			Source code for the entire system is available on <a href="https://github.com/spupyrev/gmap">Github</a>.
			A dataset of real-world graphs and networks used for our experiments can be downloaded <a href="{% url 'maps:datasets' %}">here</a>.
		</p>

	</div>
{% endblock %}

maps/templates/hyperbolic.html
<!DOCTYPE html>
<html>
  <head>
    <title>Hyperbolic Canvas Example</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="../../static/css/hyperbolic/example.css">
    <link rel="icon" type="image/png" href="images/favicon.png">
  </head>
  <body>
    <div id="hyperbolic-canvas"></div>

    <script src="../../static/openlayers/OpenLayers-min.js"></script>

    <script type="application/javascript" src="../../static/js/hyperbolic_canvas.js"></script>

    <script src="../../static/script/colors_map.dot"></script>

    <script src="../../static/js/math.js"></script>

    <script src="../../static/js/graphlib-dot.js"></script>

    <script src="../../static/js/dotparser.min.js"></script>

    <script type="text/javascript">
      var getQueryVariable = function (variable) {
        // https://css-tricks.com/snippets/javascript/get-url-variables/
        var query = window.location.search.substring(1);
        var vars = query.split("&");
        for (var i=0;i<vars.length;i++) {
          var pair = vars[i].split("=");
          if(pair[0] == variable){return pair[1];}
        }
        return('poincare_disk');
      };

      var ready = function (fn) {
        if (document.readyState != 'loading'){
          fn();
        } else {
          document.addEventListener('DOMContentLoaded', fn);
        }
      };

      ready(function () {
        var scriptName = getQueryVariable('script');
        var script = document.createElement('script');
        script.onload = function () {
          var canvas = HyperbolicCanvas.create('#hyperbolic-canvas', scriptName);
          HyperbolicCanvas.scripts[scriptName](canvas);
        };
        script.onerror = function () {
          var canvas = HyperbolicCanvas.create('#hyperbolic-canvas', scriptName);
          alert('No script found with the name "' + scriptName + '".');
        };

        script.src = "../../static/scripts/" + scriptName + '.js';
        document.body.appendChild(script);
      });
    </script>
  </body>
</html>

maps/templates/index.html
{% extends "base.html" %}

{% block title %}{{ block.super }}{% endblock %}

{% block js %}
{{ block.super }}
{% load static %}
<script type="text/javascript" src="{% get_static_prefix %}js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/jquery.cookie.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/dotparser.min.js"></script>
<script type="text/javascript">

function pasteStaticGraph(graph) {
	var ta = document.getElementById("dotfile");
	var path = "{% get_static_prefix %}graphs/" + graph;

	$.get(path, function (resp) {
		ta.value = resp;
	});
}

function checkTextArea(form)
{
	var content = form.dotfile.value.trim();
	if (content == "")
	{
		form.dotfile.focus();
		return false;
	}

	try
	{
		if (content.length <= 250000)
			DotParser.parse(content);
	}
	catch (err)
	{
		alert("Input is not a valid dot string: '" + err.message + "'");
		form.dotfile.focus();
		return false;
	}

	return true;
}

function toggleAdvanced(first_load) {
	var dv = document.getElementById("map_advanced_options");
	var el = document.getElementById("adv_link");

	if (first_load) {
		if ($.cookie("show-adv") != '1') return;
	}

	if (dv.className.indexOf("hide") == -1) {
		dv.className += " hide";
		el.innerText = "Show Advanced Options";
		$.cookie("show-adv", '0', { expires: 1 })
	}
	else {
		dv.className = dv.className.replace(" hide", "");
		el.innerText = "Hide Advanced Options";
		$.cookie("show-adv", '1', { expires: 1 })
	}
}

</script>
{% endblock %}

{% block content %}
<div style="height:115px; margin-top:0px; text-align: center">
	<img alt="GMap" height="95" src="{% get_static_prefix %}img/logo_gmap.png" width="272" style="padding-top:15px" />
</div>
<form method="post" action="{% url 'maps:request_map' %}" accept-charset="UTF-8" onsubmit="return checkTextArea(this)">
	{% csrf_token %}
	<div>
		<div class="wide center">
			<textarea name="dotfile" id="dotfile" class="wide" spellcheck="false" autofocus="autofocus" maxlength="10000000" placeholder="Paste a DOT file..."></textarea>
			<div >
				<font style="color:#999">...or try an example:</font>
				<a class="small" onclick="pasteStaticGraph('sample.gv')">Sample</a>,
				<a class="small" onclick="pasteStaticGraph('COLORS_50.gv')">Colors</a>,
				<a class="small" onclick="pasteStaticGraph('TRADE_150.gv')">TradeLand</a>,
				<a class="small" onclick="pasteStaticGraph('MUSIC_250.gv')">MusicLand</a>,
				<a class="small" onclick="pasteStaticGraph('RECIPES_350.gv')">Recipes</a>,
				<a class="small" onclick="pasteStaticGraph('BOOK_500.gv')">BookLand</a>,
				<a class="small" onclick="pasteStaticGraph('univ.gv')">Universities</a>
			</div>
		</div>

		<div style="margin:10px">
			<table class="wide center"><tbody>
					<tr>
						<td style="width: 20%">
						</td>
						<td style="width: 60%">
							<div style="text-align: center">
								<input id='submit' value='Create Map' type='submit' class="btn btn-primary"/>
							</div>
						</td>
						<td style="width: 20%">
							<a class="small" onclick="toggleAdvanced(false)" id="adv_link">Show Advanced Options</a>
						</td>
					</tr>
			</tbody></table>
		</div>

	</div>

</form>
{% endblock %}